### ISSUE TITLE
Seeking visa advice

### ISSUE THREAD

**Issue by cjbarber** [mcgd/project-ellis#26]
I'd like help.

I'm from Australia, I graduated from Stanford in June '16. My OPT runs out July 2017. I'm currently working for myself under post-completion OPT (first 12 months, not STEM OPT).

I'm currently uncertain and a bit anxious about the next step of my visa situation (STEM OPT vs O-1 vs E-3) and I'd love to be able to get some strategic help from someone to feel less uncertain. If finances weren't a concern I'd do an O-1 right away. 

I've avoided leaving the country since the new administration, as I've had to go through secondary processing twice in the past, once that ended up just being a SEVIS software issue, and once for an unknown reason that was scary but completely fine in the end - and I really don't like the thought of secondary processing with the new admin. In an ideal world, I'd get a solution that I feel 100% great about where I don't feel like I have to go through secondary processing every time I enter.

I'm not sure if I'm okay to ask here as I'm not from a directly affected country of the ban.

Thanks for operating this service, watching the repo, and everything.

**Comment by aboodman** [comment]
Hi Chris,

I run a small software startup that employs an Australian FT on the E-3 visa. I worked with Jackson and Hertogs (http://www.jackson-hertogs.com/) to obtain the visa. They have been amazing and I'd highly recommend them. I'm happy to refer you if that would be helpful. I bet they'd do an initial phone call or two free.

**Comment by mcgd** [comment]
Hi @cjbarber thank you. I will refer you to Lisa Speigel at Duane Morris. She is one of the best immigration attorneys in the United States. She is an ally of Project Ellis and your legal fees with her will be covered by Project Ellis. Please email her at lspeigel@duanemorris.com and tell her I sent you. Please keep me closely posted. You are not alone in this.

**Comment by cjbarber** [comment]
Wow. Emailed. Not sure what to say other than thank you @mcgd. Will keep you posted.

And thanks Aaron

**Comment by aboodman** [comment]
np, @mcgd's offer greatly beats mine, but email me at aa@attic.io anytime if you still want the intro.

**Comment by grantph** [comment]
I can't comment on the other visa classes, but the E-3 is surprisingly easy, and in case anyone comes across this thread:

1. A US employer submits an LCA request via the [Dept of Labor iCert website](https://icert.doleta.gov) There is some trickiness with the form, so you should expect to submit it, and have it rejected once or twice. It is important to show that the specialty occupation pays at least, or higher than market rate (can't be seen to be stealing local jobs).  Thankfully, it's usually processed within 5 days - so allow 2-3 weeks for rejections & fixes.

2. Once the LCA is issued, draft a letter of offer and provided it to the Australian applicant. They then complete a [DS-160 form online](http://www.ustraveldocs.com/au/au-niv-ds160info.asp), pay the visa fee, and set an appointment in Melbourne, Sydney, or Perth.

3. The applicant turns up for their interview with LCA, letter of offer, 4 yr degree/transcript or equiv. work experience, DS-160 receipt, etc. and answer 3-4 questions like "where are you working?", "what will you be doing?", "where will you live?" which eventually leads to them approving it, and they'll mail the passport back in a few days.

The typical turn around for the entire process is 2-4 weeks. I'm surprised this isn't used more by Silicon Valley companies because the E-3 offers a huge talent pool that is being underutilized.

**Comment by mcgd** [comment]
Thanks, all. I am going to close this issue. @cjbarber if you need to, please either reopen or open a new issue.

**Comment by lindseywig** [comment]
Hi @cjbarber, on behalf of Project Ellis, were you able to connect with Lisa Speigel to talk about your visa situation? Please let us know if you had any complications or have more questions.
